import Head from "next/head";
import styles from "../styles/global.module.scss";
import Button from "./components/Button";
import Radio from "./components/Radio";
import Check from "./components/Check";
import RadioButton from "./components/RadioButton";

/* SCSS еще будет дорабатываться по ходу выполнения проекта, 
пока просто скопировала из фигмы, не снижайте за это, пожалуйста */
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Тесты</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>*не работает клик по Radio, так как обработчик в RadioButton*</div>
        <Check checked={false} disabled={false} />
        <Radio checked={false} disabled={false} />
        <div></div>
        <RadioButton
          checked={false}
          disabled={false}
          text="Романа Мстиславича"
        />
        <Button text="создать игру" disabled={false} />
      </main>
    </div>
  );
}
